Adding WAR File verification

diff --git a/.github/workflows/ecohub.yml b/.github/workflows/ecohub.yml
--- a/.github/workflows/ecohub.yml
+++ b/.github/workflows/ecohub.yml
@@ -31,6 +31,15 @@ jobs:
         run: |
           mkdir -p /app/jenkins
           wget https://get.jenkins.io/war-stable/latest/jenkins.war -O /app/jenkins/jenkins.war
+          
+      - name: Verify Jenkins WAR file
+          run: |
+            if [ ! -f "/app/jenkins/jenkins.war" ]; then
+              echo "Error: Jenkins WAR file not found at /app/jenkins/jenkins.war"
+              exit 1
+            fi
+            echo "Jenkins WAR file exists."
+            unzip -t /app/jenkins/jenkins.war
 
       - name: Run Jenkinsfile
         uses: jenkinsci/jfr-container-action@master
